# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(-1, 29, 1090, 25))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(167, 229, 255);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.edit_searchLine = QtWidgets.QLineEdit(Form)
        self.edit_searchLine.setGeometry(QtCore.QRect(90, 32, 900, 18))
        self.edit_searchLine.setObjectName("edit_searchLine")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 31, 28, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(28, 31, 31, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(59, 31, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.button_sex = QtWidgets.QPushButton(Form)
        self.button_sex.setGeometry(QtCore.QRect(1000, 31, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_sex.setFont(font)
        self.button_sex.setObjectName("button_sex")
        self.button_close = QtWidgets.QPushButton(Form)
        self.button_close.setGeometry(QtCore.QRect(1050, 4, 18, 18))
        self.button_close.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.button_close.setText("")
        self.button_close.setObjectName("button_close")
        self.button_scale = QtWidgets.QPushButton(Form)
        self.button_scale.setGeometry(QtCore.QRect(1027, 4, 18, 18))
        self.button_scale.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    \n"
"    background-color: rgb(255, 238, 0);\n"
"}")
        self.button_scale.setText("")
        self.button_scale.setObjectName("button_scale")
        self.button_roll = QtWidgets.QPushButton(Form)
        self.button_roll.setGeometry(QtCore.QRect(1004, 4, 18, 18))
        self.button_roll.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(43, 255, 6);\n"
"}")
        self.button_roll.setText("")
        self.button_roll.setObjectName("button_roll")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "<<"))
        self.pushButton_4.setText(_translate("Form", ">>"))
        self.pushButton_5.setText(_translate("Form", "⟳"))
        self.button_sex.setText(_translate("Form", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
