# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1080, 720)
        self.button_back = QtWidgets.QPushButton(Main)
        self.button_back.setGeometry(QtCore.QRect(0, 31, 28, 20))
        self.button_back.setObjectName("button_back")
        self.button_forward = QtWidgets.QPushButton(Main)
        self.button_forward.setGeometry(QtCore.QRect(28, 31, 31, 20))
        self.button_forward.setObjectName("button_forward")
        self.button_refresh = QtWidgets.QPushButton(Main)
        self.button_refresh.setGeometry(QtCore.QRect(59, 31, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_refresh.setFont(font)
        self.button_refresh.setObjectName("button_refresh")
        self.button_sex = QtWidgets.QPushButton(Main)
        self.button_sex.setGeometry(QtCore.QRect(1000, 31, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_sex.setFont(font)
        self.button_sex.setObjectName("button_sex")
        self.button_close = QtWidgets.QPushButton(Main)
        self.button_close.setGeometry(QtCore.QRect(1050, 4, 18, 18))
        self.button_close.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.button_close.setText("")
        self.button_close.setObjectName("button_close")
        self.button_scale = QtWidgets.QPushButton(Main)
        self.button_scale.setGeometry(QtCore.QRect(1027, 4, 18, 18))
        self.button_scale.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    \n"
"    background-color: rgb(255, 238, 0);\n"
"}")
        self.button_scale.setText("")
        self.button_scale.setObjectName("button_scale")
        self.button_roll = QtWidgets.QPushButton(Main)
        self.button_roll.setGeometry(QtCore.QRect(1004, 4, 18, 18))
        self.button_roll.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(43, 255, 6);\n"
"}")
        self.button_roll.setText("")
        self.button_roll.setObjectName("button_roll")
        self.button_searchCondition = QtWidgets.QPushButton(Main)
        self.button_searchCondition.setGeometry(QtCore.QRect(1042, 31, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_searchCondition.setFont(font)
        self.button_searchCondition.setText("")
        self.button_searchCondition.setObjectName("button_searchCondition")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.button_back.setText(_translate("Main", "<<"))
        self.button_forward.setText(_translate("Main", ">>"))
        self.button_refresh.setText(_translate("Main", "⟳"))
        self.button_sex.setText(_translate("Main", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
