# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1080, 720)
        self.edit_searchLine = QtWidgets.QLineEdit(Main)
        self.edit_searchLine.setGeometry(QtCore.QRect(94, 32, 900, 18))
        self.edit_searchLine.setObjectName("edit_searchLine")
        self.button_sex = QtWidgets.QPushButton(Main)
        self.button_sex.setGeometry(QtCore.QRect(1000, 31, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_sex.setFont(font)
        self.button_sex.setObjectName("button_sex")
        self.button_searchCondition = QtWidgets.QPushButton(Main)
        self.button_searchCondition.setGeometry(QtCore.QRect(1042, 31, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_searchCondition.setFont(font)
        self.button_searchCondition.setText("")
        self.button_searchCondition.setObjectName("button_searchCondition")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.button_sex.setText(_translate("Main", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
